config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :users
  resources :players
  resources :leagues do
    resources :teams do 
      resources :players, :controller => "team_players" do
        get 'assign', on: :collection
      end
    end
    resources :games
    resources :tournaments
  end 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :league
  belongs_to :local_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"

  validates :league, presence: true
  validates :date_and_time, presence: true
  validates :local_team, presence: true
  validates :local_score, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :away_team, presence: true
  validates :away_score, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :teams_are_different

  def teams_are_different
    if (local_team_id == away_team_id) 
      errors.add("Teams must be different")
    end
  end

  def result
    local_score <=> away_score
  end

  def winner
    case result
    when 1
      local_team
    when -1
      away_team
    else 
      nil
    end
  end 

  def loser
    case result
    when 1
      away_team
    when -1
      local_team
    else 
      nil
    end
  end

end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :user, :foreign_key => 'manager_id'
  has_many :teams, dependent: :destroy
  has_many :games, dependent: :destroy
  has_many :tournaments, dependent: :destroy

  validates :name, presence: true
  validates :sport, presence: true
  validates :manager_id, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :user
  has_many :team_players
  has_many :teams, through: :team_players
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    first_name + " " + last_name
  end 

end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user, :foreign_key => 'coordinator_id'
  belongs_to :league
  has_many :team_players
  has_many :players, through: :team_players

  validates :name, presence: true
  validates :coordinator_id, presence: true

  def games
    league.games.where(local_team_id: id).or(Game.where(away_team_id: id))
  end

  def stats
    stats = Hash.new {|h,k| h[k]=[]}
    
    games.each do |game|
      if game.winner.nil?
        stats["draws"] << game
      elsif game.winner.id == id
        stats["wins"] << game
      elsif game.loser.id == id
        stats["losses"] << game
      end
    end
    stats["score"] = (stats["wins"].length * 3) +  stats["draws"].length
    stats
  end 
end

app/models/team_player.rb
class TeamPlayer < ApplicationRecord
  # use a normal table instead of a join table https://andycroll.com/ruby/be-suspicious-of-join-tables/
  belongs_to :team
  belongs_to :player
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :league
  has_many :games

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :player
    has_many :leagues, :foreign_key => 'manager_id'
    has_many :teams, :foreign_key => 'coordinator_id'

    accepts_nested_attributes_for :player

    validates :username, presence: true
    validates :password, presence: true
    validates :password, confirmation: { case_sensitive: true }

    def first_name
        player.first_name
    end
  
    def last_name
      player.last_name
    end

    def full_name
        player.full_name
    end
    
    def email
        player.email
    end    
      
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def new
    @league = League.find(params[:league_id])
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @league = League.find(params[:league_id])
    @game = @league.games.create!(game_params)
    
    redirect_to league_path(@league)
  end
    
  private
    def game_params
      params.require(:game).permit(:date_and_time, :local_team_id, :local_score, :away_team_id, :away_score)
    end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @leagues = League.all
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
    @leagues = League.all
  end

  def show
    @league = League.find(params[:id])
    @tournament = Tournament.new
  end

  def new
    @league = League.new
  end

  def create
    @user = User.find_by(username: league_params[:manager_username])
    new_league_params = league_params
    new_league_params[:manager_id] = current_user.id
    @league = League.new(new_league_params)

    if @league.save
      redirect_to @league
    else
      render :new
    end
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])
    league_params[:manager_id] = current_user.id

    if @league.update(league_params)
      redirect_to @league
    else
      render :edit
    end
  end

  def destroy
    @league = League.find(params[:id])
    if @league.destroy
      redirect_to root_path
    else 
      render :show
    end
  end

  private
    def league_params
      params.require(:league).permit(:name, :sport, :manager_username, :manager_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  
  def new
    @league = League.find(params[:league_id])
    @team = Team.new
  end

  def show
    @team = Team.find(params[:id])
  end

  def create
    @league = League.find(params[:league_id])
    @team = @league.teams.create(team_params)
    
    redirect_to league_path(@league)
  end

  def edit
    @league = League.find(params[:league_id])
    @team = Team.find(params[:id])
  end

  def update
    @league = League.find(params[:league_id])
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to league_team_path(@team)
    else
      render :edit
    end
  end
    
  def destroy
    @league = League.find(params[:league_id])
    @team = @league.teams.find(params[:id])
    if @team.destroy
      redirect_to league_path(@league)
    else 
      render :show
    end
  end
    
  private
    def team_params
      params.require(:team).permit(:name, :icon, :coordinator_id)
    end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @user.build_player
  end

  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else 
      render :show
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, player_attributes: [:id, :first_name, :last_name, :email, :photo])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_players_helper.rb
module TeamPlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.slim
= form_with model: [ @league, @game ] do |form|

  div
    = form.label :date_and_time 
    br
    = form.datetime_local_field :date_and_time
    br  
      - game.errors.full_messages_for(:name).each do |message| 
        div = message 
  
  table
    tr
      th = form.label :local_team
      th = form.label :local_score
      th = form.label :away_score
      th = form.label :away_team
    tr  
      td = collection_select :game, :local_team_id, @league.teams, :id, :name, prompt: true
      td = form.number_field :local_score, min: 0
      td = form.number_field :away_score, min: 0 
      td = collection_select :game, :away_team_id, @league.teams, :id, :name, prompt: true
  br  
  div
    = form.submit 

app/views/games/_list.html.slim
table border="1"
  tr 
    th colspan="2" Home 
    th colspan="2" 
    th colspan="2" Away
  - games.each do |game|
    tr 
      td colspan="6" style="text-align: center;" = game.date_and_time 
    tr 
      td 
        img src="#{game.local_team.icon}" alt="#{game.local_team}" width="80px" /
      td = link_to game.local_team.name, [game.local_team.league, game.local_team]
      td = game.local_score 
      td = game.away_score
      td = link_to game.away_team.name, [game.away_team.league, game.away_team]
      td 
        img src="#{game.away_team.icon}" alt="#{game.away_team}" width="80px" /
    tr

app/views/games/new.html.slim
= render "home/header"

h1 Add Game

= render "form", game: @game

app/views/leagues/_form.html.slim
= form_with model: league do |form|

  div
    = form.label :name 
    br
    = form.text_field :name 
    br  
      - league.errors.full_messages_for(:name).each do |message| 
        div = message 

  div
    = form.label :sport 
    br
    = form.select :sport, ['Football', 'Rugby', 'Basketball', 'Handball', 'Hockey', 'Volleyball', 'Cricket']
    br
      - league.errors.full_messages_for(:sport).each do |message| 
        div = message 
  
  div
    = form.submit 

app/views/leagues/_list.html.slim
.ul
  - leagues.each do |league|
    li = link_to league.name, league

app/views/leagues/edit.html.slim
= render "home/header"

h1 Edit League

= render "form", league: @league

app/views/leagues/index.html.slim
= render "home/header"

h1 Leagues
p Welcome to our Leagues

= render "list", leagues: @leagues
  
br
= link_to "New League", new_league_path

app/views/leagues/new.html.slim
= render "home/header"

h1 New League

= render "form", league: @league

app/views/leagues/show.html.slim
= render "home/header"

h1 #{@league.name}
p Welcome to the #{@league.name}. We love #{@league.sport}!
p League manager: #{link_to @league.user.username, @league.user}

- if logged_in? && is_logged_in_user?(@league.manager_id)
  h2 Options
  ul 
    li = link_to "Edit", edit_league_path 

div style="float:left; width:34%;"
  h2 Teams 
  - if @league.teams.empty? 
    p There are no teams in the league yet
  - else 
    = render "teams/table", teams: @league.teams.sort_by { |team| team.stats["score"] }.reverse!

  - if logged_in? && current_user.id == @league.manager_id  
    p #{link_to "Add new Team", new_league_team_path(@league)}

div style="float:left; width:33%;"
  h2 Games
  - if @league.games.empty? 
    p There are no games in the league yet
  - else 
    = render "games/list", games: @league.games

  - if logged_in? && current_user.id == @league.manager_id  
    p #{link_to "Add new Game", new_league_game_path(@league)}

div style="float:left; width:33%;"
  h2 Tournaments
  - if @league.tournaments.empty? 
    p There are no tournaments in the league yet
  - else 
    = render "tournaments/list", tournaments: @league.tournaments

  - if logged_in? && current_user.id == @league.manager_id  
    = render "tournaments/form", tournament: @tournament

app/views/users/_form.html.slim
= form_with model: user do |form|
  div
    = form.label :username 
    br
    = form.text_field :username 
    br  
      - user.errors.full_messages_for(:username).each do |message| 
        div = message 

  div
    = form.label :password 
    br
    = form.password_field :password 
    br
      - user.errors.full_messages_for(:password).each do |message| 
        div = message 

  div
    = form.label :password_confirmation 
    br
    = form.password_field :password_confirmation 
    br
      - user.errors.full_messages_for(:password_confirmation).each do |message| 
        div = message 

  = form.fields_for :player, @user.player do |p| 
    div
      = p.label :first_name 
      br
      = p.text_field :first_name 
      br
        - user.errors.full_messages_for(:first_name).each do |message| 
          div = message 
    
    div
      = p.label :last_name 
      br
      = p.text_field :last_name 
      br
        - user.errors.full_messages_for(:last_name).each do |message| 
          div = message 
    
    div
      = p.label :email 
      br
      = p.email_field :email 
      br  
        - user.errors.full_messages_for(:email).each do |message| 
          div = message 
    
    div
      = p.label :photo 
      br
      = p.text_field :photo 
      br  
        - user.errors.full_messages_for(:photo).each do |message| 
          div = message 

  div
    = form.submit 

app/views/users/_list.html.slim
.ul
  - users.each do |user|
    li = link_to user.username, user 

app/views/users/edit.html.slim
= render "home/header"

h1 Edit User

= render "form", user: @user

app/views/users/index.html.slim
= render "home/header"

h1 Users
= render "list", users: @users
br
= link_to "Register", new_user_path

app/views/users/new.html.slim
= render "home/header"

h1 New User

= render "form", user: @user

app/views/users/show.html.slim
= render "home/header"

h1 #{@user.username}
= render "players/player", player: @user.player

- unless @user.leagues.empty?
  h2 Leagues 
  = render "leagues/list", leagues: @user.leagues

- unless @user.teams.empty?
  h2 Teams 
  = render "teams/list", teams: @user.teams


- if logged_in? && is_logged_in_user?(@user.id)
  h2 Options
  ul 
    li = link_to "Edit", edit_user_path